language: node_js
node_js:
  - "6"
  - "8"
  - "10"
# cache dependencies between jobs (on a per-runtime-version basis)
cache: yarn
before_script: yarn build
script:
  - yarn lint
  # reduce process creation on Travis builds
  - yarn test --runInBand
